SECourse/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
import postman
from SECourse import settings
from SESite import views
from SESite.admin import admin_site
admin.autodiscover()
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^myadmin/', admin_site.urls),
    url(r'^$',views.index,name="index"),
    url(r'^Register$',views.Register,name="Register"),
    url(r'^Login',views.Login,name="Login"),
    url(r'^Logout',views.Logout,name="Logout"),
    url(r'nopremission',views.NoPermission,name="NoPermission"),
    url(r'^NoticeBoard$',views.NoticeBoard,name="NoticeBoard"),
    url(r'CourseMaterials$',views.CourseMaterials,name="CourseMaterials"),
    url(r'CourseMaterialspdfpreview(?P<fileid>\d+)$',views.CourseMaterials_preview,name="pdf_preview"),
    url(r'ScoreConsti$', views.Course_Intro, name="CourseIntro"),
    url(r'CourseIntro$', views.Course_Intro, name="CourseIntro"),
    url(r'TAIntro$', views.TA_Intro, name="TAIntro"),
    url(r'teacher_msg$', views.TA_Intro, name="TAIntro"),
    url(r'ta_msg$', views.TA_Intro, name="TAIntro"),
    url(r'AccountInfo$',views.Account_Info,name="AccountInfo"),
    url(r'change_account$',views.Change_Account,name="Change_Account"),
    url(r'AssignHomework$',views.AssignHomework,name="AssignHomework"),
    url(r'^Grade$',views.Grade,name="Grade"),
    url(r'HomeworkAndGrades$',views.HomeworkAndGrades,name="HomeworkAndGrades"),
    url(r'^ShowGrade$',views.ShowGrade,name="ShowGrade"),
    url(r'ChooseClass$',views.ChooseClass,name="ChooseClass"),
    url(r'^forum/', include('pybb.urls', namespace='pybb')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^importstudent',views.import_student,name='importstudent'),
    url(r'^deletestu',views.delete_stu,name="deletestu"),
    url(r'^TeacherIntroduction',views.TeacherIntroduction,name="TeacherIntroduction"),
    url(r'^AddtInfo',views.AddtInfo,name="AddtInfo"),
    url(r'^DeletetInfo',views.DeletetInfo,name="DeletetInfo"),
    url(r'^JoinedClass',views.join_class,name="joinclass"),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/pybb/breadcrumb.html
{% load url from future %}
{% load i18n pybb_tags %}
<ul class='breadcrumb'>
    {% include "pybb/breadcrumb_top_extra_crumb.html" %}
    <li><a href="{% url 'pybb:index' %}">{% trans "Home" %}</a></li>
    {% if object %}
        {% if object.get_parents %}
            {% for obj in object.get_parents %}
                <li>{% pybb_link obj %}</li>
            {% endfor %}
        {% endif %}
        {% if extra_crumb %}
            <li>{% pybb_link object %}</li>
        {% else %}
            <li>{{ object }}</li>
        {% endif %}
    {% endif %}
    {% if extra_crumb %}
        <li>{% trans extra_crumb %}</li>
    {% endif %}
</ul>

templates/pybb/form.html
{% load bootstrap %}
{% csrf_token %}

{{ form|bootstrap }}

<input type="hidden" name="next" value="{{ next }}" />

templates/pybb/form_field.html
{% load bootstrap %}

{{ field|bootstrap }}